## Encoding categorical data

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/dataset/customerpurchase.csv')
df


age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

there is no need of column(age & gender) now, beacause we have not studied onehot encoder (applied on these 2 column) if studied, then also it is very hectic work  to work seperatley on all columns.
TO AVOID, this hectic work scikit learn has a class (COLUMN TRANSFORMER).

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()


review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

whatever is doing on feature scaling
FIRST MOST IMPORTANT THING -> train test split


In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
x_train

review education
14     Poor        PG
34  Average    School
5   Average    School
4   Average        UG
30  Average        UG
1      Poor        UG
13  Average    School
25     Good    School
37  Average        PG
45     Poor        PG
26     Poor        PG
17     Poor        UG
18     Good    School
20  Average    School
40     Good    School
3      Good        PG
38     Good    School
47     Good        PG
27     Poor        PG
21  Average        PG
19     Poor        PG
32  Average        UG
16     Poor        UG
8   Average        UG
6      Good    School
36     Good        UG
23     Good    School
12     Poor    School
24  Average        PG
2      Good        PG
48     Good        UG
10     Good        UG
44  Average        UG
7      Poor    School
31     Poor    School
49     Good        UG
46     Poor        PG
43     Poor        PG
11     Good        UG
39     Poor        PG

In [17]:
from sklearn.preprocessing import OrdinalEncoder


In [20]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [21]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

FIT ON TRAIN but transform on both test and train

In [22]:
x_train= oe.transform(x_train)
x_test=oe.transform(x_test)

In [23]:
x_train

array([[0., 2.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.]])

In [24]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le= LabelEncoder()

In [28]:
le.fit(y_train)

LabelEncoder()

In [29]:
le.classes_    #doubt

array(['No', 'Yes'], dtype=object)

In [30]:
y_train= le.transform(y_train)

In [31]:
y_test=le.transform(y_test)

In [32]:
y_train


array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0])

In [36]:
y_test

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1])